### ISSUE TITLE
Help please :)

### ISSUE THREAD

**Issue by AndreyNazarchuk** [BeATz-UnKNoWN/ModPE_Scripts#1]
At this part of he code:
menuLayout.addView(button);

```
        //Add more buttons in this section
```

I cannot figure out how to add a new button because I don't know what is the EXACT code for it, Plus This is confusing me:
menuLayout.addView(button);
I cannot figure out if that's the start of the new button or the end of the old one

**Comment by beatzunknown** [comment]
var button = new android.widget.Button(ctx);
button.setText("Button");
button.setOnClickListener(new android.view.View.OnClickListener({
onClick: function(viewarg){
//Your Code
}
}));
menuLayout.addView(button);

This is your first button. To make another one you would "clone" it with another variable name. Let's call it button2.

var button2 = new android.widget.Button(ctx);
button2.setText("Button");
button2.setOnClickListener(new android.view.View.OnClickListener({
onClick: function(viewarg){
//Your Code
}
}));
menuLayout.addView(button2);

**Comment by AndreyNazarchuk** [comment]
Thanks so much! No wonder it was crashing!

**Comment by PEMapModder** [comment]
Maybe you should close this issue...

**Comment by AndreyNazarchuk** [comment]
Lol you're everywhere

**Comment by PEMapModder** [comment]
@AndreyNazarchuk I just visited your page and saw your contributions :D

**Comment by AndreyNazarchuk** [comment]
Can you help me again please? :)
This code:

function newLevel(){
    if(!ModPE.readData("test"));{
    clienMessage(ChatColor.GOLD + "Lantern, " + ChatColor.WHITE = "by " + ChatColor.BLUE + "andynazay153" + ChatColor.GREEN + "Loaded Successfully!");
    ModPE.saveData("test", "Test");
    }
}
//                                       Bottom                   Top                     North                    South                    East                     West 
Block.defineBlock(180, "Lantern", [["redstone_lamp_on", 0], ["redstone_lamp_on", 0], ["redstone_lamp_on", 0], ["redstone_lamp_on", 0], ["redstone_lamp_on", 0], ["redstone_lamp_on", 0]]);
Block.setDestroyTime(180,2);
Block.setShape(180,0.5,0,0.5,0.5,0.5,0.5);
Block.setLightLevel(180, 16);
function destroyBlock(x, y, z){
var blockId = Level.getTile(x, y, z);
if(blockId == 180){
preventDefault();
Level.destroyBlock(x, y, z, true);
}
}

Is crashing for no reason at all, It does not even say whats wrong in the error, except: evaluator exception and stuff like that.
I think it might be because of 
Block.setShape but I don't know
Thanks :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1:

**Comment by beatzunknown** [comment]
if(!ModPE.readData("test"));{

What is that semicolon doing there? Tell me if it works now, I left the MCPE modding community so I don't know ModPE that well anymore.

And ChatColor.WHITE = "by" doesn't seem right.

**Comment by AndreyNazarchuk** [comment]
Oh lol, Idk how the ; got there, and the = was sop posed to be a +

**Comment by AndreyNazarchuk** [comment]
One of my mods is importing, but then crashes a few seconds after I open a
world, I just added 200 lines of code, though idk why it would crash a few
seconds after opening a world, I mean, it has already checked for updates
and it loads the GUI when the game is still generating the world, so idk,
nothing is sop posed to be proccesing at the time, and it's before the
chunks generate. Do you possibly have an idea of why it is doing this
injustice to me? Thanks!

**Comment by AndreyNazarchuk** [comment]
Heres a link:

>    https://www.dropbox.com/s/dtw3j6rr7g1un4c/Kits.js?dl=0

**Comment by PEMapModder** [comment]
@AndreyNazarchuk shoghicp did that too :D

**Comment by AndreyNazarchuk** [comment]
@PEMapModder did what? Asked for help?

**Comment by AndreyNazarchuk** [comment]
I'm pretty sure its something wrong with this, because when I remove this it does not crash:

 if(checkForUpdate==false) {
        print("Checking for updates");
        ctx.runOnUiThread(new java.lang.Runnable({
            run: function() {
                try {
                    checkVersion();
                }
                catch(err) {
                    clientMessage("§8[IS] Error: \n"+err);
                }
            }
        }));
        checkForUpdate=true;
    }
    if(updateWindow) {
        ctx.runOnUiThread(new java.lang.Runnable({
            run: function() {
                try {
                    updateVersion();
                }
                catch(err) {
                    clientMessage("§8[IS] Error: \n" + err);
                }
            }
        }));
        updateWindow=false;
    }

**Comment by PEMapModder** [comment]
@AndreyNazarchuk I meant if(boolean);{}

**Comment by beatzunknown** [comment]
The problem could also be in your updateVersion or checkVersion function. I don't see you crossing the Java bridge in those functions.

**Comment by AndreyNazarchuk** [comment]
Hmm..... But there is no update, the update file in my GitHub is the same
as the version in the code

**Comment by AndreyNazarchuk** [comment]
Well, I had someone test it for me and it did not crash, so I think it was
because my testing device is old, thanks.
