### ISSUE TITLE
Github tips for comments, maybe the readme.md as well

### ISSUE THREAD

**Issue by CtrlAltCuteness** [BeATz-UnKNoWN/ModPE_Scripts#2]
Using the backtick character (it is the key that is shared with ~ but without shift on a standard U.S. English keyboard at least, and since I cannot assume which keyboard you use, I cannot be sure) when typing in comments and readme.md files in repositories, as long as you aren't using a full blown editor without the source view of what you are typing enabled, you can use it to show code very well. use one at the start and finish of a one-line command for a short code where I use a visual here to show where they go (backtick)var a=123;(backtick) which turns into `var a=123;`.

For a multi-line, I know some coding things support it but I don't know here as I type this from my phone, it is 3 backticks without anything between the three for the start and also for the finish. Make sure to put an empty line after the starting triple backticks unless you know what you are doing.
(bt)(bt)(bt)
// line 1
// line 2
// ... more please!
(bt)(bt)(bt)

```
// line 1
// line 2
// ... more please!
```

**Comment by beatzunknown** [comment]
Ok. Thanks!
